---
hero_image: images/brain-game.png
theme: red
duration: 2
listed: false
ingredient: false
copyedit: false
curriculum: 1, design-0, programming-1, phys-comp-0, manufacture-0, community-0
title: Gêm i'r Ymennydd
description: Dysga sut i greu cwis.
original_url: https://codeclubprojects.org/en-GB/scratch/brain-game
interests: games
technologies: scratch
site_areas: projects
hardware: ''
software: scratch
version: 3
last_tested: 2017-01-01
steps: 
- title: Cyflwyniad
- title: Creu cwestiynau
- title: 'Her: Newid gwisgoedd'
- title: 'Her: Ychwanegu sgôr'
- title: Gemau lluosog
- title: "Her: Dechrau'r gêm2"
- title: Ychwanegu graffeg
- title: 'Her: Perffeithio dy animeiddiad'
- title: 'Her: Cerdd a Sain'
- title: 'Her: Ras i 10 o bwyntiau'
- title: 'Her: Sgrin cyfarwyddiadau'