---
hero_image: images/brain-game.png
theme: red
duration: 2
listed: false
ingredient: false
copyedit: false
curriculum: 1, design-0, programming-1, phys-comp-0, manufacture-0, community-0
title: Gehirntraining
description: Lerne, wie man ein Quiz produziert.
original_url: https://projects.raspberrypi.org/en/projects/brain-game
interests: games
technologies: scratch
site_areas: projects
hardware: ''
software: scratch
version: 3
last_tested: 2017-01-01
steps: 
- title: Einführung
- title: Fragen zusammenstellen
- title: 'Aufgabe: Kostüm ändern'
- title: 'Aufgabe: Eine Punktzahl hinzufügen'
- title: Mehrfache Spiele
- title: 'Aufgabe: Start-Bildschirm'
- title: Grafik hinzufügen
- title: 'Aufgabe: Verbesserte Animation'
- title: 'Aufgabe: Sound und Musik'
- title: 'Aufgabe: Wettrennen zu 10 Punkten'
- title: 'Aufgabe: Anweisungsbildschirm'