---
hero_image: images/brain-game.png
theme: red
duration: 2
listed: false
ingredient: false
copyedit: false
curriculum: 1, design-0, programming-1, phys-comp-0, manufacture-0, community-0
title: Mozgalica
description: Nauči kako da napraviš kviz.
original_url: https://codeclubprojects.org/en-GB/scratch/brain-game
interests: games
technologies: scratch
site_areas: projects
hardware: ''
software: scratch
version: 3
last_tested: 2017-01-01
steps:
  - title: Uvod
  - title: Izrada pitanja
  - title: 'Izazov: Promjena kostima'
  - title: 'Izazov: Dodavanje bodova'
  - title: Više igara
  - title: 'Izazov: Početni ekran'
  - title: Dodavanje grafika
  - title: 'Izazov: Poboljšana animacija'
  - title: 'Izazov: Zvuk i muzika'
  - title: 'Izazov: Trka do 10 bodova'
  - title: 'Izazov: Ekran sa uputstvima'
